### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'padEnd')

### ISSUE THREAD

**Issue by twocolors** [twocolors/node-red-contrib-midea-hvac#10]
```
20 Jul 13:11:51 - [info] Starting modified nodes
TypeError: Cannot read properties of undefined (reading 'padEnd')
    at Flow.start (/home/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:254:62)
    at start (/home/node-red/node_modules/@node-red/runtime/lib/flows/index.js:394:33)
20 Jul 13:11:51 - [info] Started modified nodes
```

https://github.com/twocolors/node-red-contrib-midea-hvac/blob/master/nodes/hvac.js#L9

**Comment by twocolors** [comment]
fix https://github.com/twocolors/node-red-contrib-midea-hvac/commit/8160efddd4afb8f31b02363cab2e8d54a399ae34
